### PR TITLE
bug: emit `ParentReady` for ancestor of finalized block 

### LINKED ISSUE #97: Issue `ParentReady` upon finalizing block
Analogous to https://github.com/anza-xyz/alpenglow/pull/404.

### PR DESCRIPTION
**Pull request by qkniep**
When seeing a new finalized block, Pool should check whether we issued a `ParentReady` for this window already. If not a `ParentReady` should be issued for the first slot of the window.

This ensures that we correctly enter the window when catching up based on finalized blocks, setting the timeouts and voting notar or skip for the slots. Especially during standstill this is critical. Without this, if enough validators are in this state, the network may not ever recover from standstill.

Closes #97.

### CODE REVIEW

**Comment by qkniep** [comment]
Added `mark_finalized()` function to the `ParentReadyTracker` now. Internally, it just marks the parent of the finalized block as notarized-fallback and all slots between finalized block and its parent as skipped. It then emits all the new `ParentReady`s. Instead this could just emit a single `ParentReady` (for the window of the finalized slot). This should not make a big difference unless there is a long stretch of skipped leaders before the finalized slot.

**Comment by qkniep** [comment]
I Implemented a `FinalityTracker`, which is a very basic data structure that is now used inside pool to keep track of when a block is (1) available, (2) notarized, (3) finalized (previously we were only tracking the highest finalized slot, without caring about notarization and block being available). The `FinalityTracker` then returns the finalized block ID and its parent's ID, which can then be passed to the `ParentReadyTracker`, for issuing the potentially missing `ParentReady`.

@akhi3030 It's still ugly and I would need to add testing but I would be interested in what you think about this approach, specifically looking at the last commit.

**Comment by akhi3030** [comment]
To make sure I understand the problem correctly, let's say that the window consists of slots 10, 11, 12, 13.  I join the network at slot 12 and missed the parent ready for slot 10.  I then see the finalized block for slot 12.  So now we want to issue a parent ready for 10 so that I can setup the timers for the later slots.  Is that roughly correct?

Question: doesn't need to be handled in this PR but do we need to adjust how we set the timer for the remaining slots?  i.e. if set the timers as normally, in the example above, the timer for slot 13 would fire much later.  Not sure what kind of challenges that can create.

File: src/consensus/pool/finality_tracker.rs [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+    }
+}
+
+impl Default for FinalityTracker {
+    fn default() -> Self {
+        Self {
+            parents: BTreeMap::new(),
+            notarized: BTreeMap::new(),
+            finalized: BTreeSet::new(),
+            highest_finalized: Slot::genesis(),
```
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs]: maybe we can define a default for `Slot` to return genesis, then we can just derive default for this struct.

**Comment by qkniep** [comment]
Implementing the last test above, I just realized that I'm still missing a fundamental part (which also appears in your example), where the first block of the window may only be finalized implicitly. Thus we don't just need (1) the finalized block, (2) its notar cert, (3) its final cert, but also (4) any ancestor blocks in the same window.

> Is that roughly correct?

Yes, in that case we would want to issue ParentRead(10, slot(b), hash(b)) where block b is the ancestor of the block in slot 12 with the highest slot number < 10.

> Can you expand a bit on what do you not like about the `FinalityTracker`?

I think what I currently don't like is that it seem to be so simple, that there might be a nice way to do entirely without it and just have some additional stuff in `Pool`. However, thinking about it maybe that's not a good idea: Pool is already complicated enough and especially when also considering the logic that is still missing (see first paragraph above) `FinalityTracker` may become more non-trivial as well.

> do we need to adjust how we set the timer for the remaining slots?

Trying to fire the timeouts for individual slots early seems like over-engineering to me: This should very rarely happen. If it happens, we are already entering the window late, for all we know we could have been offline for minutes, trying to set timeouts exactly right seems like a lost cause.

However, if we really wanted to do something, it should certainly be safe to deduct `DELTA_BLOCK` for each block up to and including the finalized block in the window from all timeouts for the window. So, in your example, we could deduct `3 * DELTA_BLOCK`.

**Comment by akhi3030** [comment]
makes sense.  Thanks for the additional context.  I agree that at the moment `FinalityTracker` does seem quite simple.  Let's see what it looks like once you have added the additional case of implicit finalization.

**Comment by qkniep** [comment]
Not entirely sure if my introduction of an `enum FinalizationStatus` in the `FinalityTracker` made things more or less understandable. But now it should also support implicit finalization of blocks and implicit skipping of slots. And now I would say `FinalityTracker` is no longer trivial, it actually became more complex than expected.

File: src/consensus/pool/parent_ready_tracker/parent_ready_state.rs [hunk 2]
```diff
@@ -86,12 +95,21 @@ impl ParentReadyState {
...
-            IsReady::Ready(block_ids) => Either::Left(*block_ids.first().unwrap()),
+            IsReady::Ready(block_ids) => {
+                assert!(!block_ids.is_empty());
+                if block_ids.len() == 1 {
+                    Either::Left(block_ids[0])
+                } else {
+                    let mut block_ids = block_ids.to_vec();
+                    block_ids.sort();
+                    Either::Left(block_ids[0])
+                }
```
Comment (akhi3030) [inline src/consensus/pool/parent_ready_tracker/parent_ready_state.rs]:
```suggestion
                block_ids.sort();
                Either::Left(block_ids[0])
```

This seems to cargo check.

File: src/consensus/pool/finality_tracker.rs [hunk 3]
```diff
@@ -0,0 +1,305 @@
...
+pub struct FinalizationEvent {
+    /// Directly finalized block, if any.
+    pub(super) finalized: Option<BlockId>,
+    /// Any implicitly finalized blocks.
+    pub(super) implicitly_finalized: Vec<BlockId>,
+    /// Any implicitly skipped slots.
+    pub(super) implicitly_skipped: Vec<Slot>,
+}
+
+impl FinalityTracker {
```
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs:64]: nit: I prefer to group the struct definitions and impls together.  Not a big deal though.

File: src/consensus/pool/finality_tracker.rs [hunk 4]
```diff
@@ -0,0 +1,305 @@
...
+    /// Adds the given `parent` for the given `block`.
+    ///
+    /// Handles possibly resulting implicit finalizations.
+    ///
+    /// Returns a [`FinalizationEvent`] that contains information about newly finalized slots.
+    pub fn add_parent(&mut self, block: BlockId, parent: BlockId) -> FinalizationEvent {
```
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs:70]: nit: I would be worried that someone might accidentally switch block and parent around.  Could we add some debug asserts (e.g. parent.slot < block.slot)?

File: src/consensus/pool/finality_tracker.rs [hunk 5]
```diff
@@ -0,0 +1,305 @@
...
+use crate::crypto::Hash;
+use crate::types::Slot;
+
+/// Tracks finality of blocks.
+#[derive(Default)]
+pub struct FinalityTracker {
+    /// Current finalization status for each slot.
+    status: BTreeMap<Slot, FinalizationStatus>,
+    /// Maps blocks to their parents.
+    parents: BTreeMap<BlockId, BlockId>,
```
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs:33]: probably future work.  Thinking about https://github.com/qkniep/alpenglow/pull/99/files#r2290476466, I wonder if we should use a new type for BTreeMap here which will validate all inserts.  Might be an overkill though.

File: src/consensus/pool/finality_tracker.rs [hunk 6]
```diff
@@ -0,0 +1,305 @@
...
+    /// Handles possibly resulting implicit finalizations.
+    ///
+    /// Returns a [`FinalizationEvent`] that contains information about newly finalized slots.
+    pub fn add_parent(&mut self, block: BlockId, parent: BlockId) -> FinalizationEvent {
+        let mut event = FinalizationEvent::default();
+        self.parents.insert(block, parent);
+        if let Some(status) = self.status.get(&block.0)
+            && let FinalizationStatus::FinalizedAndNotarized(block_hash)
+            | FinalizationStatus::ImplicitlyFinalized(block_hash) = status
+            && block.1 == *block_hash
```
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs]:
```suggestion
            && &block.1 == block_hash
```

nit.  I think the compiler will probably produce the same code in both cases.  But it seems better like this as at least the code claims that we are not copying.

File: src/consensus/pool/finality_tracker.rs [hunk 7]
```diff
@@ -0,0 +1,305 @@
...
+        {
+            self.handle_implicitly_finalized(block.0, parent, &mut event);
```
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs]: I struggled a bit with this function:

- the tuple indexing was difficult to think about.
- The if statement took some time to parse
- The if statement does not handle other variants and if we modify the enum, we might miss something.

So I came up with the following.  A bit more verbose but hopefully more readable.

```suggestion
        let (slot, block_hash) = block;
        if let Some(status) = self.status.get(&slot) {
            match status {
                FinalizationStatus::FinalizedAndNotarized(hash)
                | FinalizationStatus::ImplicitlyFinalized(hash) => {
                    if &block_hash == hash {
                        self.handle_implicitly_finalized(block.0, parent, &mut event);
                    }
                }

                FinalizationStatus::Notarized(_)
                | FinalizationStatus::Finalized
                | FinalizationStatus::ImplicitlySkipped => (),
            }

```

File: src/consensus/pool/finality_tracker.rs [hunk 8]
```diff
@@ -0,0 +1,305 @@
...
+    ///
+    /// If the block was newly finalized, handles resulting implicit finalizations.
+    ///
+    /// Returns a [`FinalizationEvent`] that contains information about newly finalized slots.
+    pub fn mark_fast_finalized(&mut self, slot: Slot, block_hash: Hash) -> FinalizationEvent {
+        let mut event = FinalizationEvent::default();
+        if let Some(status) = self.status.get(&slot) {
+            match status {
+                FinalizationStatus::FinalizedAndNotarized(_) => {
+                    return event;
```
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs]: nit: I would just return `FinalizationEvent::default()` here and define event after the if statement instead of on the top.  The way the code is right now, it seems like we may modify event in the if statement and use the modifications below.

File: src/consensus/pool/finality_tracker.rs [hunk 9]
```diff
@@ -0,0 +1,305 @@
...
+
+impl FinalityTracker {
+    /// Adds the given `parent` for the given `block`.
+    ///
+    /// Handles possibly resulting implicit finalizations.
+    ///
+    /// Returns a [`FinalizationEvent`] that contains information about newly finalized slots.
+    pub fn add_parent(&mut self, block: BlockId, parent: BlockId) -> FinalizationEvent {
+        let mut event = FinalizationEvent::default();
+        self.parents.insert(block, parent);
```
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs]: What are the implications of if the block already had a parent?

File: src/consensus/pool/finality_tracker.rs (hunk 6 above)
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs]: What are the implications of the block hash not matching?

File: src/consensus/pool/finality_tracker.rs [hunk 10]
```diff
@@ -0,0 +1,305 @@
...
+            match status {
+                FinalizationStatus::Notarized(_)
+                | FinalizationStatus::FinalizedAndNotarized(_)
+                | FinalizationStatus::ImplicitlyFinalized(_)
+                | FinalizationStatus::ImplicitlySkipped => event,
+                FinalizationStatus::Finalized => {
+                    self.status
+                        .insert(slot, FinalizationStatus::FinalizedAndNotarized(block_hash));
+                    self.handle_finalized((slot, block_hash), &mut event);
+                    event
```
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs]: same comment as above.  I would define the event above this line and in the rest of the arms return `FinalizationEvent::default()`

File: src/consensus/pool/finality_tracker.rs [hunk 11]
```diff
@@ -0,0 +1,305 @@
...
+    /// - any potentially implicitly finalized blocks, AND
+    /// - any implicitly skipped slots.
+    fn handle_finalized(&mut self, finalized: BlockId, event: &mut FinalizationEvent) {
+        event.finalized = Some(finalized);
+        if let Some(parent) = self.parents.get(&finalized) {
+            self.handle_implicitly_finalized(finalized.0, *parent, event);
+        }
+    }
+
+    /// Handles the indirect finalization of the given block.
```
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs:214]: If the node joined the network after being absent for a long time, this function could recurse a lot.  There might be a potential for running out of stack space.  Probably not something we need to worry about in this PR but could be something to track in an issue at least.

**Review by akhi3030 — COMMENTED** [review]
I didn't review the whole patch as I felt like the number of comments was getting a bit out of hand.  

They are a bit overlapping so let me know if some of them don't make sense.

File: src/consensus/pool/finality_tracker.rs (hunk 4 above)
Comment (qkniep) [reply src/consensus/pool/finality_tracker.rs:70]: good suggestion, added the same assert for `Pool::add_block()`

File: src/consensus/pool/finality_tracker.rs (hunk 9 above)
Comment (qkniep) [reply src/consensus/pool/finality_tracker.rs]: `add_parent()` is idempotent if the same parent is added twice because `handle_implicit_finalization` is idempotent, a different parent should never be added, we could add an assertion for that

Comment (qkniep) [reply src/consensus/pool/finality_tracker.rs]: added an assertion and early return now, thus making idempotence of `add_parent()` very explicit

File: src/consensus/pool/finality_tracker.rs (hunk 6 above)
Comment (qkniep) [reply src/consensus/pool/finality_tracker.rs]: it just means we added a parent relation between block b and parent(b), whereas the block that was finalized is b' instead, so we don't care about b and its parent... this can happen, for example, if we just received block b from Rotor, but also already saw notar+final certs for b'

File: src/consensus/pool/finality_tracker.rs (hunk 5 above)
Comment (qkniep) [reply src/consensus/pool/finality_tracker.rs:33]: seems overkill to me, `FinalityTracker` is already just a glorified wrapper around the two `BTreeMap`s

File: src/consensus/pool/finality_tracker.rs (hunk 11 above)
Comment (qkniep) [reply src/consensus/pool/finality_tracker.rs:214]: I don't think we need to worry about stack space, the compiler should be able to optimize this tail recursion, otherwise we could also write it as a loop explicitly. Even when catching up, we would only trigger implicit finalizations at most as quickly as we repair the ancestor chain of the directly finalized block. The only case where this should ever trigger a massive chain, is if for some reason we *first* repair a long chain of blocks and only then see the finalization for the last block in the chain.

File: src/consensus/pool/finality_tracker.rs (hunk 7 above)
Comment (qkniep) [reply src/consensus/pool/finality_tracker.rs]: I went for something slightly different but hopefully just as readable

File: src/consensus/pool/finality_tracker.rs (hunk 3 above)
Comment (qkniep) [reply src/consensus/pool/finality_tracker.rs:64]: so far we are mostly consistent in preferring the other style, I have no problem with moving to the struct+impl style, but this should be a separate refactoring PR then

File: src/consensus/pool/finality_tracker.rs [hunk 12]
```diff
@@ -0,0 +1,344 @@
...
+    /// Handles possibly resulting implicit finalizations.
+    ///
+    /// Returns a [`FinalizationEvent`] that contains information about newly finalized slots.
+    pub fn add_parent(&mut self, block: BlockId, parent: BlockId) -> FinalizationEvent {
+        assert!(block.0 > parent.0);
+        if let Some(p) = self.parents.get(&block) {
+            assert!(p == &parent);
+            return FinalizationEvent::default();
+        }
+        self.parents.insert(block, parent);
```
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs]: We are doing two accesses into the map here.  We could either check the return value from `insert` or use the `entry` API.

File: src/consensus/pool/finality_tracker.rs [hunk 13]
```diff
@@ -0,0 +1,344 @@
...
+    }
+
+    /// Marks the given block as notarized.
+    ///
+    /// Handles possibly resulting direct finalization of the block.
+    /// Further, also handles any possibly resulting implicit finalizations.
+    ///
+    /// Returns a [`FinalizationEvent`] that contains information about newly finalized slots.
+    pub fn mark_notarized(&mut self, slot: Slot, block_hash: Hash) -> FinalizationEvent {
+        if let Some(status) = self.status.get(&slot) {
```
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs]: we are accessing the map a couple of different times in this function.  I wonder if the entries api will be more readable.

File: src/consensus/pool/finality_tracker.rs [hunk 14]
```diff
@@ -0,0 +1,344 @@
...
+            match status {
+                FinalizationStatus::Notarized(_)
+                | FinalizationStatus::FinalizedAndNotarized(_)
+                | FinalizationStatus::ImplicitlyFinalized(_)
+                | FinalizationStatus::ImplicitlySkipped => FinalizationEvent::default(),
+                FinalizationStatus::Finalized => {
```
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs]: I think when we first marked the slot as finalized, we called `handle_finalized` there.  So calling it again here should strictly speaking not be necessary?  Or I am missing something.

File: src/consensus/pool/finality_tracker.rs [hunk 15]
```diff
@@ -0,0 +1,344 @@
...
+    ///
+    /// Handles possibly resulting direct finalization of a block in this slot.
+    /// Further, also handles any possibly resulting implicit finalizations.
+    ///
+    /// Returns a [`FinalizationEvent`] that contains information about newly finalized slots.
+    pub fn mark_finalized(&mut self, slot: Slot) -> FinalizationEvent {
+        if let Some(status) = self.status.get(&slot) {
+            match status {
+                FinalizationStatus::Finalized
+                | FinalizationStatus::FinalizedAndNotarized(_)
```
Comment (akhi3030) [inline src/consensus/pool/finality_tracker.rs]: We can get multiple finalizations for a slot if we got fast finalization and slow one?  Are there other scenarios?

**Review by akhi3030 — COMMENTED** [review]
A partial review of just the finality_tracker.  I will review the changes in the pool either tonight or tomorrow.

File: src/consensus/pool/finality_tracker.rs (hunk 14 above)
Comment (qkniep) [reply src/consensus/pool/finality_tracker.rs]: This should be correct as is, the idea is: We want to call `handle_finalized()` only after the block is notarized and the slot is finalized. Notarization and finalization can happen in any order, so in `mark_notarized()` should only call it if the slot is already finalized, and `mark_finalized()` only if a block in the slot was notarized before.

It might be possible to make this more clear in a few places. Do you think referring to finalized slot and finalized block would be clearer, e.g. `FinalizationStatus::FinalizedSlot` and `FinalizationStatus::FinalizedBlock(hash)` and `handle_finalized_block()`.

File: src/consensus/pool/finality_tracker.rs (hunk 12 above)
Comment (qkniep) [reply src/consensus/pool/finality_tracker.rs]: changed in a bunch of places, see https://github.com/qkniep/alpenglow/pull/99/commits/321657f5e01190e8426b1ee9feb07bd1b96e1698

File: src/consensus/pool/finality_tracker.rs (hunk 15 above)
Comment (qkniep) [reply src/consensus/pool/finality_tracker.rs]: yes, if `FinalityTracker` is used correctly there should be at most two triggers (or even just one) to finalize a block in a given slot, however there are potentially many ways finalization can be triggered within pool (constructing FastFinal cert ourselves, receiving it, constructing Notar+Final cert ourselves, receiving those, and then there are many different certs) most of which should be ignored if they come after the first one

I think low-level components like `FinalityTracker` (and other parts of the code) ideally should not break if these events are triggered more than once by some higher-level component

File: src/consensus/pool/finality_tracker.rs (hunk 14 above)
Comment (akhi3030) [reply src/consensus/pool/finality_tracker.rs]: >  Do you think referring to finalized slot and finalized block would be clearer, e.g. FinalizationStatus::FinalizedSlot and FinalizationStatus::FinalizedBlock(hash) and handle_finalized_block().


Yes, I think that can definitely help!

File: src/consensus/pool/finality_tracker.rs (hunk 15 above)
Comment (akhi3030) [reply src/consensus/pool/finality_tracker.rs]: that makes sense.  I agree that these components should be resilient to such events as well.

File: src/consensus/pool/parent_ready_tracker.rs [hunk 16]
```diff
@@ -77,10 +64,11 @@ impl ParentReadyTracker {
     /// Marks the given slot as skipped.
     ///
     /// Returns a list of any newly connected parents.
-    ///
-    /// This should only ever be called once for any specific slot.
     pub fn mark_skipped(&mut self, slot: Slot) -> Vec<(Slot, BlockId)> {
```
Comment (akhi3030) [inline src/consensus/pool/parent_ready_tracker.rs:67]: The changes really improve the readability of the function.  Thank you.

File: src/consensus/pool.rs [hunk 17]
```diff
@@ -141,10 +144,16 @@ impl PoolImpl {
...
-                self.highest_notarized_fallback_slot =
-                    slot.max(self.highest_notarized_fallback_slot);
+                info!(
+                    "notarized(-fallback) block {} in slot {}",
+                    &hex::encode(block_hash)[..8],
+                    slot
+                );
+                if matches!(cert, Cert::Notar(_)) {
+                    let finalization_event = self.finality_tracker.mark_notarized(slot, block_hash);
+                    self.parent_ready_tracker
```
Comment (akhi3030) [inline src/consensus/pool.rs]: to help future readers, should we add a comment about why we can ignore the returned parent ready here.

Comment (qkniep) [reply src/consensus/pool.rs]: good catch, that was actually a bug! wrapped the two calls in a `handle_finalization()` function to prevent this
