### PR TITLE
fix: correctly account for first slice in crashed leader timeout

### LINKED ISSUE #65: Crashed leader timeout buffer
Right now the crashed-leader timeout is triggered after `DELTA_TIMEOUT` has elapsed. This is correct assuming the leader would send out a slice immediately when their leader window starts.

### PR DESCRIPTION
**Pull request by qkniep**
This introduces the additional parameter `DELTA_FIRST_SLICE` a short timeout for producing the first slice. The leader makes sure to only take at most this amount of time for the first slice. In return, we can account for the crashed leader timeout correctly. See issue #65 for more info.

Closes #65.

### CODE REVIEW

File: src/consensus/block_producer.rs [hunk 1]
```diff
@@ -165,11 +170,21 @@ where
                 None
             };
 
-            // cap timeout for each slice to `DELTA_BLOCK`
-            // makes sure optimistic block production yields before timeout would expire
-            let time_for_slice = duration_left.min(self.delta_block);
+            let time_for_slice = if slice_index == SliceIndex::first() {
```
Comment (akhi3030) [inline src/consensus/block_producer.rs]:
```suggestion
            let time_for_slice = if slice_index.is_first() {
```

File: src/consensus/block_producer.rs [hunk 2]
```diff
@@ -254,8 +269,12 @@ where
             } else {
                 None
             };
-            let (payload, maybe_duration) =
-                produce_slice_payload(&self.txs_receiver, parent, duration_left).await;
+            let (payload, maybe_duration) = if slice_index == SliceIndex::first() {
```
Comment (akhi3030) [inline src/consensus/block_producer.rs]:
```suggestion
            let (payload, maybe_duration) = if slice_index.is_first() {
```

File: src/consensus/block_producer.rs [hunk 3]
```diff
@@ -254,8 +269,12 @@ where
...
+                let time_for_slice = duration_left.min(self.delta_first_slice);
+                produce_slice_payload(&self.txs_receiver, parent, time_for_slice).await
+            } else {
+                produce_slice_payload(&self.txs_receiver, parent, duration_left).await
+            };
```
Comment (akhi3030) [inline src/consensus/block_producer.rs]: Maybe something like below has less code duplication.


```suggestion
            let time_for_slice = if slice_index.is_first() {
                duration_left.min(self.delta_first_slice)
            } else {
                duration_left
            };
            let (payload, maybe_duration) = produce_slice_payload(&self.txs_receiver, parent, time_for_slice).await;
```

File: src/consensus/block_producer.rs (hunk 2 above)
Comment (akhi3030) [reply src/consensus/block_producer.rs]: Also should we duplicate the comment from above: i.e. "maybe sure first slice is produced on time".

File: src/consensus/block_producer.rs [hunk 4]
```diff
@@ -165,11 +170,21 @@ where
                 None
             };
 
-            // cap timeout for each slice to `DELTA_BLOCK`
-            // makes sure optimistic block production yields before timeout would expire
-            let time_for_slice = duration_left.min(self.delta_block);
+            let time_for_slice = if slice_index == SliceIndex::first() {
+                // make sure first slice is produced on time
+                // TODO: this can be made more accurate, only needed if production of first slice
```
Comment (akhi3030) [inline src/consensus/block_producer.rs:175]: For my understanding: it can still be the case that the leader has not seen parent ready but the other nodes have seen it.  In that case, the way the code is currently would make sense, i.e. the leader should not delay producing the first slice longer.

File: src/consensus/votor.rs [hunk 5]
```diff
@@ -252,12 +253,16 @@ impl<A: All2All + Sync + Send + 'static> Votor<A> {
         );
         let sender = self.event_sender.clone();
         tokio::spawn(async move {
-            tokio::time::sleep(DELTA_TIMEOUT).await;
+            tokio::time::sleep(DELTA_TIMEOUT + DELTA_FIRST_SLICE).await;
```
Comment (akhi3030) [inline src/consensus/votor.rs:256]: I guess we need to create a similar issue in agave to handle this scenario.  I think it is still doing it the old way.

**Review by akhi3030 — APPROVED** [review]
LGTM.   Minor comments.  Disabled auto-merge.

File: src/consensus/votor.rs (hunk 5 above)
Comment (qkniep) [reply src/consensus/votor.rs:256]: it was part of this issue https://github.com/anza-xyz/alpenglow/issues/243

File: src/consensus/block_producer.rs (hunk 4 above)
Comment (qkniep) [reply src/consensus/block_producer.rs:175]: not really, without the optimistic handover the leader would only even start producing the block after seeing the parent ready, the timeouts capture that

File: src/consensus/votor.rs (hunk 5 above)
Comment (akhi3030) [reply src/consensus/votor.rs:256]: We might need a new issue.  https://github.com/anza-xyz/alpenglow/blob/master/votor/src/timer_manager/timers.rs#L61.  We are generating the crashed leader timeout after DELTA_BLOCK.

Comment (qkniep) [reply src/consensus/votor.rs:256]: immediately after DELTA_TIMEOUT, before the first DELTA_BLOCK, if I am reading that correctly, but yes, either would warrant a new issue
